CREATE TABLE IF NOT EXISTS users (
    algorithmScore INTEGER NOT NULL DEFAULT 0,
    id TEXT PRIMARY KEY NOT NULL,
    displayName TEXT,
    fanflair TEXT,
    avatar TEXT,
    banner TEXT,
    status TEXT,
    about TEXT,
    tags TEXT DEFAULT '[]',
    pronouns TEXT,
    birthdate TEXT,
    birthdateVisibility TEXT NOT NULL DEFAULT 'private',
    foundedDate TEXT,
    foundedDateVisibility TEXT NOT NULL DEFAULT 'default',
    theme TEXT DEFAULT '4819203746571029',
    isAuraEnabled INTEGER NOT NULL DEFAULT 0,
    auraType TEXT NOT NULL DEFAULT 'flow',
    auraPrimary TEXT DEFAULT '#ce1616',
    auraSecondary TEXT DEFAULT '#000000',
    type TEXT NOT NULL DEFAULT 'user',
    flags TEXT NOT NULL DEFAULT '0',
    isDeveloper INTEGER NOT NULL DEFAULT 0,
    isExplicit INTEGER NOT NULL DEFAULT 0,
    visibility TEXT NOT NULL DEFAULT 'private',
    sendMessages TEXT NOT NULL DEFAULT 'default',
    sendComments TEXT NOT NULL DEFAULT 'default',
    presence TEXT NOT NULL DEFAULT 'offline',
    presenceVisibility TEXT NOT NULL DEFAULT 'default',
    lastActive TEXT,
    createdDate TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
