CREATE TABLE IF NOT EXISTS users (
    algorithmScore INTEGER NOT NULL DEFAULT 0,
    id TEXT PRIMARY KEY NOT NULL,
    displayName TEXT,
    fanflair TEXT,
    avatar TEXT,
    animatedAvatar TEXT,
    banner TEXT,
    status TEXT,
    about TEXT,
    markdown TEXT,
    tags TEXT DEFAULT '[]',
    pronouns TEXT,
    birthDate TEXT,
    birthDateVisibility TEXT NOT NULL DEFAULT 'friends',
    foundedDate TEXT,
    foundedDateVisibility TEXT NOT NULL DEFAULT 'default',
    location TEXT,
    theme TEXT DEFAULT '4819203746571029',
    isAuraEnabled INTEGER NOT NULL DEFAULT 0,
    auraType TEXT NOT NULL DEFAULT 'flow',
    auraPrimary TEXT DEFAULT '#ce1616',
    auraSecondary TEXT DEFAULT '#000000',
    type TEXT NOT NULL DEFAULT 'user',
    flags TEXT NOT NULL DEFAULT '0',
    isDeveloper INTEGER NOT NULL DEFAULT 0,
    isSensitive INTEGER NOT NULL DEFAULT 0,
    isMature INTEGER NOT NULL DEFAULT 0,
    areFriendRequestsEnabled INTEGER NOT NULL DEFAULT 1,
    visibility TEXT NOT NULL DEFAULT 'private',
    sendMessages TEXT NOT NULL DEFAULT 'public',
    sendComments TEXT NOT NULL DEFAULT 'public',
    presence TEXT NOT NULL DEFAULT 'online',
    isOnline INTEGER NOT NULL DEFAULT 0,
    lastActive TEXT,
    createdDate TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);
