export type SortByType = 
    | "recommended"
    | "limited"
    | "verified"
    | "trending"
    | "popularDesc"
    | "popularAsc"
    | "recent"
    | "newest"
    | "oldest"
    | "nameAsc"
    | "nameDesc"
