CREATE TABLE IF NOT EXISTS sessions (
    sessionId TEXT PRIMARY KEY,
    userId TEXT,
    geoIpFirstFetch TEXT,
    geoIpLatestFetch TEXT,
    geoIpLatestFetchExpireDate TEXT,
    userAgent TEXT,
    inviteCode TEXT,
    accessToken TEXT UNIQUE,
    accessTokenExpireDate TEXT,
    mfaToken TEXT UNIQUE,
    mfaTokenExpireDate TEXT,
    mfaStatus TEXT,
    sessionToken TEXT UNIQUE,
    sessionTokenExpireDate TEXT,
    isTerminated INTEGER DEFAULT 0,
    totalDuration INTEGER DEFAULT 0,
    isConnected INTEGER DEFAULT 0,
    firstConnectedDate TEXT DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    lastConnectedDate TEXT
);